In [2]:
!pip install selenium bs4 pandas

Collecting selenium
  Downloading selenium-4.4.3-py3-none-any.whl (985 kB)
     |████████████████████████████████| 985 kB 703 kB/s eta 0:00:01
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: pandas in /home/ade/anaconda3/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: urllib3[socks]~=1.26 in /home/ade/anaconda3/lib/python3.9/site-packages (from selenium) (1.26.9)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Requirement already satisfied: certifi>=2021.10.8 in /home/ade/anaconda3/lib/python3.9/site-packages (from selenium) (2021.10.8)
Collecting trio~=0.17
  Downloading trio-0.21.0-py3-none-any.whl (358 kB)
     |████████████████████████████████| 358 kB 4.1 MB/s eta 0:00:01
Requirement already satisfied: beautifulsoup4 in /home/ade/anaconda3/lib/python3.9/site-packages (from bs4) (4.11.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/ade/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/ade/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in /home/ade/anaconda3/lib/python3.9/site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /home/ade/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: idna in /home/ade/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (3.3)
Collecting outcome
  Downloading outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
Collecting async-generator>=1.9
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Requirement already satisfied: sniffio in /home/ade/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in /home/ade/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in /home/ade/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (21.4.0)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /home/ade/anaconda3/lib/python3.9/site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Collecting h11<1,>=0.9.0
  Downloading h11-0.13.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 708 kB/s eta 0:00:011
Requirement already satisfied: soupsieve>1.2 in /home/ade/anaconda3/lib/python3.9/site-packages (from beautifulsoup4->bs4) (2.3.1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1272 sha256=a63c9b1970d25829747c1b2ace4ea58e68fd16313a857310ebe1e50207ab18dd
  Stored in directory: /home/ade/.cache/pip/wheels/73/2b/cb/099980278a0c9a3e57ff1a89875ec07bfa0b6fcbebb9a8cad3
Successfully built bs4
Installing collected packages: outcome, h11, async-generator, wsproto, trio, trio-websocket, selenium, bs4
Successfully installed async-generator-1.10 bs4-0.0.1 h11-0.13.0 outcome-1.2.0 selenium-4.4.3 trio-0.21.0 trio-websocket-0.9.2 wsproto-1.2.0

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

import pandas as pd
import requests
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException
import time

from bs4 import BeautifulSoup

In [2]:
driver = webdriver.Chrome('/home/ade/Documents/TA2022/chromedriver')

/tmp/ipykernel_12011/1788907942.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('/home/ade/Documents/TA2022/chromedriver')

In [3]:
data = pd.read_csv('id_unik.csv')
data.head()

,Unnamed: 0,id,nama_pengguna
0,0,https://www.google.com/maps/contrib/1054964145...,memmzz a
1,1,https://www.google.com/maps/contrib/1017445562...,Steve Mascheri
2,2,https://www.google.com/maps/contrib/1030639642...,Mandy my PHN
3,3,https://www.google.com/maps/contrib/1036043872...,Nicholas Kaethner
4,4,https://www.google.com/maps/contrib/1092838409...,Michal Vodák

In [4]:
data.id.value_counts()

https://www.google.com/maps/contrib/100929115527739357821/reviews?hl=en-US    3
https://www.google.com/maps/contrib/114790518222081048001/reviews?hl=en-US    3
https://www.google.com/maps/contrib/105102527337291076456/reviews?hl=en-US    3
https://www.google.com/maps/contrib/102041541371716806706/reviews?hl=en-US    3
https://www.google.com/maps/contrib/104839442954895163202/reviews?hl=en-US    2
                                                                             ..
https://www.google.com/maps/contrib/111564455370005622567/reviews?hl=en-US    1
https://www.google.com/maps/contrib/105843863502729912758/reviews?hl=en-US    1
https://www.google.com/maps/contrib/106956916607546663078/reviews?hl=en-US    1
https://www.google.com/maps/contrib/115777615069412249108/reviews?hl=en-US    1
https://www.google.com/maps/contrib/106676642252942479245/reviews?hl=en-US    1
Name: id, Length: 80008, dtype: int64

In [5]:
# uniqueID = data.id.drop_duplicates()
uniqueID = data.drop_duplicates(subset=['id'])

uniqueID.id.value_counts()

https://www.google.com/maps/contrib/105496414599981678036/reviews?hl=en-US    1
https://www.google.com/maps/contrib/115401590279516602389/reviews?hl=en-US    1
https://www.google.com/maps/contrib/114334760070023613099/reviews?hl=en-US    1
https://www.google.com/maps/contrib/109282221134799552641/reviews?hl=en-US    1
https://www.google.com/maps/contrib/105240943536686526999/reviews?hl=en-US    1
                                                                             ..
https://www.google.com/maps/contrib/108081047241345816928/reviews?hl=en-US    1
https://www.google.com/maps/contrib/116742568171205379653/reviews?hl=en-US    1
https://www.google.com/maps/contrib/109234535613095702326/reviews?hl=en-US    1
https://www.google.com/maps/contrib/102574809772579463344/reviews?hl=en-US    1
https://www.google.com/maps/contrib/106676642252942479245/reviews?hl=en-US    1
Name: id, Length: 80008, dtype: int64

In [6]:
import re
import numpy as np

unikList = uniqueID['id'].tolist()
clean_uniqueID = []
for i in unikList:
    n_data = re.sub("[^0-9]", "", i)
    clean_uniqueID.append(n_data)

uniqueID['id_user'] = clean_uniqueID
uniqueID.head()

/tmp/ipykernel_12011/676506282.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uniqueID['id_user'] = clean_uniqueID

,Unnamed: 0,id,nama_pengguna,id_user
0,0,https://www.google.com/maps/contrib/1054964145...,memmzz a,105496414599981678036
1,1,https://www.google.com/maps/contrib/1017445562...,Steve Mascheri,101744556297454326387
2,2,https://www.google.com/maps/contrib/1030639642...,Mandy my PHN,103063964286933900274
3,3,https://www.google.com/maps/contrib/1036043872...,Nicholas Kaethner,103604387243309981913
4,4,https://www.google.com/maps/contrib/1092838409...,Michal Vodák,109283840916012960189

In [7]:
name =[]
img_src =[]
points =[]
level =[]
n_reviews =[]
n_photos =[]
view_photos =[]

In [8]:
df = uniqueID[2000:3000]
df

,Unnamed: 0,id,nama_pengguna,id_user
2000,2017,https://www.google.com/maps/contrib/1104141152...,INDAH TRAVELLER,110414115274561379950
2001,2018,https://www.google.com/maps/contrib/1066109462...,ig/fb wismapakuansyariahhotel,106610946228438010696
2002,2019,https://www.google.com/maps/contrib/1090771168...,Iqbal Abdurrahman Naufal,109077116889956803396
2003,2020,https://www.google.com/maps/contrib/1120042260...,Jeeshan Ifthikar,112004226025369561755
2004,2021,https://www.google.com/maps/contrib/1083710166...,Shashi Prakash,108371016634247852620
...,...,...,...,...
2995,3038,https://www.google.com/maps/contrib/1019924953...,Víctor Eduardo Avilés Romo,101992495369624611957
2996,3039,https://www.google.com/maps/contrib/1130546463...,Ashley Council,113054646372169625930
2997,3040,https://www.google.com/maps/contrib/1054688042...,Hans-Martin Jäck,105468804234295734317
2998,3041,https://www.google.com/maps/contrib/1149597441...,Beta S (Szuszu),114959744152357755606
2999,3042,https://www.google.com/maps/contrib/1161239294...,K H,116123929433708309406

In [9]:
def scrape():
    for i in df.id:
        url = i
        driver.get(url)

#         scrape poin
        try:
            in_point = driver.find_element("xpath",'//*[@id="uc9cqe-n1UuX-XUufyc-Wt0bsf-hUbt4d"]/span[3]/jsl').text
            points.append(in_point)
        except:
            points.append("NaN")
        
        print(len(points))
        
#         scrape level
        try:
            in_level = driver.find_element("xpath",'//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]/div[2]/div[3]/span').text
            level.append(in_level)
        except:
            level.append("NaN")
            
#         scrape n_review
        try:
            in_n_reviews = driver.find_element("xpath",'//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[6]/div[1]/div[2]/span/span[2]').text
            n_reviews.append(in_n_reviews)
        except:
            n_reviews.append("NaN")
        
#         otw img
        try:
            select = driver.find_element("xpath",'/html/body/div[3]/div[9]/div[9]/div/div/div[1]/div[2]/div/div[1]/div/div/div[5]/div/div/button[2]/div/div[1]')
            select.click()
#             time.sleep(2)
        except:
            pass
        
#         scrape photos
        try:
            in_n_photos = driver.find_element("xpath",'/html/body/div[3]/div[9]/div[9]/div/div/div[1]/div[2]/div/div[1]/div/div/div[6]/div[1]/div[2]/span[1]/span[2]').text
            n_photos.append(in_n_photos)
        except:
            n_photos.append("NaN")
        
#         scrape view img
        try:
            in_view_photos = driver.find_element("xpath",'/html/body/div[3]/div[9]/div[9]/div/div/div[1]/div[2]/div/div[1]/div/div/div[6]/div[1]/div[2]/span[2]/span[2]').text
            view_photos.append(in_view_photos)
        except:
            view_photos.append("NaN")
            
#         scrape img profil
        try:
            get_img = driver.find_element("xpath",'/html/body/div[3]/div[9]/div[9]/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]/div[2]/div[1]/div/img').get_attribute("src")
            img_src.append(get_img)
        except:
            img_src.append("NaN")
            
    print("Total scrape",len(points))

In [10]:
scrape()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
Total scrape 1000

In [11]:
print(len(n_reviews))
print(len(level))
print(len(n_photos))
print(len(view_photos))

1000
1000
1000
1000

# cek & looping scrape

In [ ]:
# df = uniqueID[:770]
# scrape()

In [14]:
# len(uniqueID)
# df = uniqueID[1340:2000]
# df

,Unnamed: 0,id,nama_pengguna,id_user
1340,1340,https://www.google.com/maps/contrib/1155085454...,Praveen Kumar,115508545408213807913
1341,1341,https://www.google.com/maps/contrib/1065487151...,Aadesh Power of law,106548715195171590999
1342,1342,https://www.google.com/maps/contrib/1175051050...,Khizer Siddique,117505105004436648397
1343,1343,https://www.google.com/maps/contrib/1137749607...,Nadia Kobuane,113774960789582996895
1344,1344,https://www.google.com/maps/contrib/1153417375...,Andrej Svec,115341737566647055161
...,...,...,...,...
1995,2012,https://www.google.com/maps/contrib/1040405576...,Enry Mazni,104040557664265982440
1996,2013,https://www.google.com/maps/contrib/1182467644...,Ahmad Soyuti Hj Sabran,118246764411906725738
1997,2014,https://www.google.com/maps/contrib/1055314204...,afrila gunadi,105531420432950425085
1998,2015,https://www.google.com/maps/contrib/1173869992...,teamsashing,117386999224265159576
1999,2016,https://www.google.com/maps/contrib/1155785647...,Zidnie Mubarok,115578564771323418518

In [12]:
df['points'] = points
df['level'] = level
df['n_reviews'] = n_reviews
df['n_photos'] = n_photos
df['view_photos'] = view_photos
df['img_src'] = img_src

/tmp/ipykernel_12011/240710253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['points'] = points
/tmp/ipykernel_12011/240710253.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['level'] = level
/tmp/ipykernel_12011/240710253.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['n_reviews'] = n_reviews
/tmp/ipykernel_12011/240710253.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['n_photos'] = n_photos
/tmp/ipykernel_12011/240710253.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['view_photos'] = view_photos
/tmp/ipykernel_12011/240710253.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['img_src'] = img_src

In [13]:
df.tail()

,Unnamed: 0,id,nama_pengguna,id_user,points,level,n_reviews,n_photos,view_photos,img_src
2995,3038,https://www.google.com/maps/contrib/1019924953...,Víctor Eduardo Avilés Romo,101992495369624611957,"20,215",Local Guide · Level 8,468 reviews · 110 ratings,"1,556","5,106,357",https://lh3.googleusercontent.com/a-/AFdZucoPX...
2996,3039,https://www.google.com/maps/contrib/1130546463...,Ashley Council,113054646372169625930,"1,973",Local Guide · Level 6,81 reviews,92,"1,667,340",https://lh3.googleusercontent.com/a-/AFdZucoaD...
2997,3040,https://www.google.com/maps/contrib/1054688042...,Hans-Martin Jäck,105468804234295734317,"1,033",Local Guide · Level 5,56 reviews · 5 ratings,55,"105,236",https://lh3.googleusercontent.com/a-/AFdZucpFa...
2998,3041,https://www.google.com/maps/contrib/1149597441...,Beta S (Szuszu),114959744152357755606,"1,862",Local Guide · Level 6,55 reviews · 34 ratings,221,"693,578",https://lh3.googleusercontent.com/a-/AFdZucrNd...
2999,3042,https://www.google.com/maps/contrib/1161239294...,K H,116123929433708309406,"4,045",Local Guide · Level 6,NaN,NaN,NaN,https://lh3.googleusercontent.com/a-/AFdZucq4a...

In [14]:
df.id[2999]

'https://www.google.com/maps/contrib/116123929433708309406/reviews?hl=en-US'

In [ ]:
# df.n_reviews[769]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 2000 to 2999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     1000 non-null   int64
 1   id             1000 non-null   object
 2   nama_pengguna  1000 non-null   object
 3   id_user        1000 non-null   object
 4   points         1000 non-null   object
 5   level          1000 non-null   object
 6   n_reviews      1000 non-null   object
 7   n_photos       1000 non-null   object
 8   view_photos    1000 non-null   object
 9   img_src        1000 non-null   object
dtypes: int64(1), object(9)
memory usage: 118.2+ KB

In [16]:
df.level.value_counts()

Local Guide · Level 6    337
Local Guide · Level 7    238
Local Guide · Level 5    189
Local Guide · Level 8     83
Local Guide · Level 4     46
                        ...
129 contributions          1
14,098 contributions       1
276 contributions          1
170 contributions          1
122 contributions          1
Name: level, Length: 80, dtype: int64

In [17]:
df.to_csv('user_detail-3000.csv')

In [18]:
# cek1 = pd.read_csv('user_detail-700.csv')
# cek2 = pd.read_csv('user_detail-1340.csv')
cek3 = pd.read_csv('user_detail-2000.csv')
cek4 = pd.read_csv('user_detail-3000.csv')

In [19]:
# print(cek1.tail(3))
# print(cek2.tail(3))
# print(cek3.tail(3))
print(cek4.tail(3))

     Unnamed: 0.1  Unnamed: 0  \
997          2997        3040
998          2998        3041
999          2999        3042

                                                    id     nama_pengguna  \
997  https://www.google.com/maps/contrib/1054688042...  Hans-Martin Jäck
998  https://www.google.com/maps/contrib/1149597441...   Beta S (Szuszu)
999  https://www.google.com/maps/contrib/1161239294...               K H

                   id_user points                  level  \
997  105468804234295734317  1,033  Local Guide · Level 5
998  114959744152357755606  1,862  Local Guide · Level 6
999  116123929433708309406  4,045  Local Guide · Level 6

                   n_reviews n_photos view_photos  \
997   56 reviews · 5 ratings       55     105,236
998  55 reviews · 34 ratings      221     693,578
999                      NaN      NaN         NaN

                                               img_src
997  https://lh3.googleusercontent.com/a-/AFdZucpFa...
998  https://lh3.googleusercontent.com/a-/AFdZucrNd...
999  https://lh3.googleusercontent.com/a-/AFdZucq4a...